version: '3'
services:
  packwiz:
    container_name: munkeawcraft-packwiz
    image: my-app/packwiz
    volumes:
      - ./apps/packwiz:/apps/packwiz:rw
    build:
      context: .
      dockerfile: ./apps/packwiz/Dockerfile
    env_file:
      - .env
    ports:
      - "23343:23343"
  mc:
    container_name: munkeawcraft-server
    image: itzg/minecraft-server:latest
    volumes:
      - ./apps/mc/munkeawcraft-server-data:/data:rw
    env_file:
      - .env
    # https://github.com/itzg/docker-minecraft-server#server-configuration
    environment:
      EULA: TRUE
      TYPE: FABRIC
      MAX_MEMORY: 2G
      MOTD: "§cmunkeawcraft"
      DIFFICULTY: easy
      ICON: "https://github.com/munkeawtoast/munkeawtoast/blob/main/pixelated-mapraw.png?raw=true"
      PACKWIZ_URL: "http://packwiz:23343/pack.toml"
      ENABLE_QUERY: false
      SNOOPER_ENABLED: false
      VIEW_DISTANCE: 10
    ports:
      - 25565:25565
      - 3331:3331/udp
    depends_on:
      - packwiz
    links:
      - packwiz