version: '3'
services:
  packwiz:
    container_name: munkeawcraft-packwiz
    image: my-app/packwiz
    build:
      context: .
      dockerfile: ./apps/packwiz/Dockerfile
    volumes:
      - ./apps/packwiz:/data:rw
    env_file:
      - .env
    ports:
      - "23343:23343"
  mc:
    container_name: munkeawcraft-server
    image: itzg/minecraft-server:latest
    volumes:
      - ./apps/mc/server-data:/data:rw
    env_file:
      - .env
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      PACKWIZ_URL: "localhost:23343/pack.toml"
    ports:
      - "25565:25565"
      - "24454:24454"
    depends_on:
      - packwiz
