name = "munkeawcraft"
author = "munkeawtoast"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd317d763577bdcb5caad92fbbe56c9b3def772b49851f7f4662761a9496f96d"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
